image: bradrydzewski/go:1.4
notify:
  email:
    recipients:
      - drone@clever.com
publish:
  catapult:
    url: $$catapult_url
    application: "shorty"
    when:
      branch: master
  docker:
    docker_host: $$docker_server
    email: $$docker_email
    username: $$docker_username
    password: $$docker_password
    image_name: clever/shorty
    registry_login: true
    tags:
      - $(git rev-parse --short HEAD)
    when:
      branch: master
services:
  - postgres
  - redis
script:
  - go get -t ./...
  - sudo apt-get install -y postgresql-client
  - createdb -h localhost -U postgres drone
  - git log --stat -n 10
  - bash integration_tests.sh
  - make build
